version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7
    environment:
      SOFTHSM_MODULE: /usr/lib/softhsm/libsofthsm2.so
    steps:
      - run: apt -y update
      - run: apt -y install swig softhsm2 libsofthsm2
      - checkout
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
